version: '3.7'
# Override service props from main `docker-compose.yml`
services:
  frontend:
    networks:
      pub1:
        ipv4_address: ${FRONTEND_IPV4_ADDRESS?}

  api:
    networks:
      pub1:
        ipv4_address: ${API_IPV4_ADDRESS?}

# roach-cert:
#   container_name: roach-cert
#   hostname: roach-cert
#   build: db/cert
#   volumes:
#     - certs-roach-0:/certs/roach-0
#     - certs-client:/certs/client

  roach-0:
    image: cockroachdb/cockroach:latest
    container_name: ${COMPOSE_PROJECT_NAME?}-roach-0
    restart: always
    hostname: roach-0
    command: start-single-node --insecure --listen-addr=roach-0:${DB_PORT} 
    # command: start-single-node --cluster-name=dp-crdb-cluster --logtostderr=WARNING --log-file-verbosity=WARNING --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --certs-dir=/certs
    volumes:
      - roach-0-data:/cockroach/cockroach-data
    #   - certs-roach-0:/certs
    # depends_on:
    #   - roach-cert
    networks:
      - backend-net

  roach-lb:
    # https://github.com/cockroachlabs-field/dynamic-haproxy
    image: timveil/dynamic-haproxy:latest
    container_name: ${COMPOSE_PROJECT_NAME?}-roach-lb
    restart: always
    hostname: roach-lb
    environment:
      - NODES=roach-0
      # - NODES=roach-0 roach-1 roach-2
    ports:
        - "${DB_PORT?}:26257"
        - "3080:8080"
        - "3081:8081"
    networks:
      - backend-net
    depends_on:
      - roach-0
    healthcheck:
      test: /bin/true
      interval: 3s
      timeout: 10s
      retries: 10

networks:
  pub1:
    external: true


