version: "3.7"
# Override service props from main `docker-compose.yml`
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV?}
      args:
        NODE_ENV: ${NODE_ENV?}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN?}
    ports:
      - "${APP_PORT?}:3040"
    volumes:
      # Local:Container mounting points
      - ./frontend:/app
      - /app/.next
      - /app/node_modules

  api:
    build:
      context: ./backend/contact
      dockerfile: ./Dockerfile
      target: ${TARGET_ENV?}
    environment:
      DEBUG: "true"
    ports:
      - "${REST_API_PORT?}:5000"
    volumes:
      - ./backend/contact:/app
      - /app/dist

  campaigns:
    build:
      context: ./backend/
      dockerfile: ./module-campaigns/Dockerfile
      # target: ${TARGET_ENV?}
    environment:
      DEBUG: "true"
    ports:
      - "${CAMPAIGN_GRPC_PORT?}:5001"

  flyway:
    build:
      context: .
      dockerfile: ./flyway/Dockerfile
    volumes:
      - ./db/migrations:/flyway/sql

  roach-0:
    image: cockroachdb/cockroach:latest
    container_name: ${COMPOSE_PROJECT_NAME?}-roach-0
    restart: always
    hostname: roach-0
    command: start-single-node --insecure --listen-addr=roach-0:${DB_PORT} 
    volumes:
      - roach-0-data:/cockroach/cockroach-data
    networks:
      - backend-net
