name: Build module-campaigns

on:
  workflow_dispatch:
  push:
    branches: "**"
    paths:
      - "backend/module-campaigns/**"
  pull_request:
    branches: [master]
    paths:
      - "backend/module-campaigns/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    defaults:
      run:
        working-directory: backend/module-campaigns

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
        env:
         ConnectionStrings__CampaignDb: Host=postgres;Port=5432;Database=app;Username=test;Password=test;Include Error Detail=true